baseURL: "https://AmlanJSarmah.github.io/A.J.Sarmah/"
languageCode: en-us
title: A.J.Sarmah
theme: PaperMod

params:

  title: A.J.Sarmah
  description: "A personal blog and portfolio of A.J.Sarmah, a linux system programmer, an aspiring ML Engineer and a student at VIT Bhopal University."
  keywords: [Blog, Portfolio, Programming]
  author: A.J.Sarmah
  
  profileMode:
    enabled: true
    title: "Amlan Jyoti (AJ) Sarmah"
    subtitle: Hello 👋 I am Amlan Jyoti Sarmah, more commonly known as AJ. I have been programming for a little over 4 years. Mostly I work with Linux System Software, currently I am learning about Machine Learning and Web Development.  
    imageUrl: "images/profile_picture.jpeg"
    imageWidth: 250 
    imageHeight: 250 
    buttons:
      - name: Blogs
        url: 

  socialIcons:
    - name: email
      url: "mailto:amlan.j.sarmah@gmail.com"
    - name: github
      url: "https://github.com/AmlanJSarmah/"
    - name: linkedin
      url: "https://linkedin.com/in/amlan-jyoti-sarmah-0aa9b8290"
    - name: twitter
      url: "https://x.com/AmlanJSarmah"

menu:
  main:
    - name: Search
      url: search/
      weight: 10
    - identifier: categories
      name: Categories
      url: 
      weight: 20
    - identifier: tags
      name: Tags
      url: 
      weight: 30
