baseURL: "https://AmlanJSarmah.github.io/A.J.Sarmah/"
languageCode: en-us
title: A.J.Sarmah
theme: PaperMod

params:

  title: A.J.Sarmah
  description: "A personal blog and portfolio of A.J.Sarmah, a linux system programmer, an aspiring ML Engineer and a student at VIT Bhopal University."
  keywords: [Blog, Portfolio, Programming]
  author: A.J.Sarmah
  
  profileMode:
    enabled: true
    title: "Amlan Jyoti (AJ) Sarmah"
    subtitle: Welcome! I'm Amlan, a seasoned Linux Systems Programmer with four years of experience. Currently, I'm pursuing a degree in AI & ML Engineering at VIT Bhopal, driven by a passion for advancing technology. Additionally, I serve as a core team member and C++ blockchain developer at Swupel PMS. My journey is fueled by a commitment to excellence and a relentless pursuit of innovation in the fields of Linux programming and machine learning.
    imageUrl: "images/dp.jpeg"
    imageWidth: 275
    imageHeight: 300
    buttons:
      - name: Blogs
        url: 
      - name: Projects
        url: 

  socialIcons:
    - name: email
      url: "mailto:amlan.j.sarmah@gmail.com"
    - name: github
      url: "https://github.com/AmlanJSarmah/"
    - name: linkedin
      url: "https://linkedin.com/in/amlan-jyoti-sarmah-0aa9b8290"

menu:
  main:
    - name: Search
      url: search/
      weight: 10
    - identifier: categories
      name: Categories
      url: 
      weight: 20
    - identifier: tags
      name: Tags
      url: 
      weight: 30
