baseURL: "https://AmlanJSarmah.github.io/A.J.Sarmah/"
languageCode: en-us
title: A.J.Sarmah
theme: PaperMod

params:

  title: A.J.Sarmah
  description: "A personal blog and portfolio of A.J.Sarmah, a linux system programmer, a hobbiest game dev and a student at VIT Bhopal University."
  keywords: [Blog, Portfolio, Programming]
  author: A.J.Sarmah
  
  profileMode:
    enabled: true
    title: "Hello World 👋"
    subtitle: >
            ### I am **A.J.Sarmah** !
              I have been a Linux System Programmer for a little over 3 years. Currently I am studying AI/ML Engineering at **VIT Bhopal University**, I am also an hobbyist game developer.    
              I am currently working at an Austrian based land digitalization project called **Swupel PMS**, and have also co-founded my own startup called **Ideabazzar**.  
    imageUrl: "images/dp.jpg"
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: Blogs
        url: 
      - name: Projects
        url: 

  homeInfoParams:
    Title: "Hello World 👋"
    Content: >
          I am **A.J.Sarmah** !
            
            - I have beem a Linux System Programmer for little over 3 years, Currently I am studying AI/ML Engineering at **VIT Bhopal University**, I am also a hobbyist game developer.
    
            - I am currently working at an Austrian based land digitalization project called **Swupel PMS**, and have also co-founded my own startup called **Ideabazzar**.
  
  socialIcons:
    - name: email
      url: "mailto:ajsarmah@tutanota.com"
    - name: github
      url: "https://github.com/AmlanJSarmah/"
    - name: linkedin
      url: "https://linkedin.com/in/amlan-jyoti-sarmah-0aa9b8290"

menu:
  main:
    - name: Search
      url: search/
      weight: 10
    - identifier: categories
      name: Categories
      url: 
      weight: 20
    - identifier: tags
      name: Tags
      url: 
      weight: 30
