baseURL: "https://AmlanJSarmah.github.io/A.J.Sarmah/"
languageCode: en-us
title: A.J.Sarmah
theme: PaperMod

params:

  title: A.J.Sarmah
  description: "A personal blog and portfolio of A.J.Sarmah, a linux system programmer, a hobbiest game dev and a student at VIT Bhopal University."
  keywords: [Blog, Portfolio, Programming]
  author: A.J.Sarmah
  
  profileMode:
    enabled: true
    title: "Hello World 👋"
    subtitle: >
            ### I am **A.J.Sarmah** !
              I am a Linux System Programmer, studying AI/ML Engineering at **VIT Bhopal**, and a hobbiest game developer. I am currently working in a Austrian based land digitalization project called **Swupel PMS**, co-founded my own startup called **Ideabazzar** and created a passionate gave development stable **The Club**.
    imageUrl: "images/dp.jpg"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Blogs
        url: 
      - name: Projects
        url: 

  homeInfoParams:
    Title: "Hello World 👋"
    Content: >
          I am **A.J.Sarmah** !
            
            - I am a Linux System Programmer, studying AI/ML Engineering at **VIT Bhopal**, and a hobbiest game developer.
    
            - I am currently working in a Austrian based land digitalization project called **Swupel PMS**, co-founded my own startup called **Ideabazzar** and a created passionate gave development stable **The Club**.
  
  socialIcons:
    - name: email
      url: "mailto:ajsarmah@tutanota.com"
    - name: github
      url: "https://github.com/AmlanJSarmah/"
    - name: twitter
      url: "https://twitter.com/AmlanJSarmah/"

menu:
  main:
    - name: Search
      url: search/
      weight: 10
    - identifier: categories
      name: Categories
      url: 
      weight: 20
    - identifier: tags
      name: Tags
      url: 
      weight: 30
