baseURL: "https://AmlanJSarmah.github.io/A.J.Sarmah/"
languageCode: en-us
title: A.J.Sarmah
theme: PaperMod

params:
  title: A.J.Sarmah
  description: "A personal blog and portfolio of A.J.Sarmah, a linux system programmer, an aspiring ML Engineer and a student at VIT Bhopal University."
  keywords: [Blog, Portfolio, Programming]
  author: A.J.Sarmah

  profileMode:
    enabled: true
    title: "Amlan Jyoti (AJ) Sarmah"
    subtitle: "the taco bell chugging programmer :)\n

      building cool software with swupel e.U."
    imageUrl: "images/profile_picture.jpeg"
    imageWidth: 150
    imageHeight: 150
    buttons:
      - name: Blogs
        url:

  socialIcons:
    - name: email
      url: "mailto:amlan.j.sarmah@gmail.com"
    - name: github
      url: "https://github.com/AmlanJSarmah/"
    - name: twitter
      url: "https://x.com/AmlanJSarmah"
    - name: linkedin
      url: "https://www.linkedin.com/in/amlan-jyoti-sarmah/"

menu:
  main:
    - name: Search
      url: search/
      weight: 10
    - identifier: categories
      name: Categories
      url:
      weight: 20
    - identifier: tags
      name: Tags
      url:
      weight: 30

caches:
  images:
    dir: :cacheDir/images
